services:
  chatbot-nginx:
    image: "chatbot-nginx"
    container_name: "chatbot-nginx"
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - chatbot-php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - "$PWD/..:/var/chatbot"
    ports:
      - "172.17.0.1:11080:80"
    networks:
      - chatbot-network

  chatbot-php:
    image: "chatbot-php"
    container_name: "chatbot-php"
    build:
      context: ../.
      dockerfile: docker/php/Dockerfile
      tags:
        - php-chatbot
    user: 1000:1000
    volumes:
      - "$PWD/..:/var/chatbot"
      - "$PWD/..:$PWD/.."
    working_dir: $PWD/..
    env_file: ../secret.env
    depends_on:
      chatbot-mariadb:
        condition: service_started
    networks:
      - chatbot-network

  chatbot-mariadb:
    image: chatbot-mariadb:latest
    container_name: "chatbot-mariadb"
    build:
      context: .
      dockerfile: mariadb/Dockerfile
      tags:
        - latest
    restart: always
    volumes: 
      - /home/debian/projet/chatbot-mariadb/_data:/var/lib/mysql
      - ../../mariabackup:/backup
    env_file:
      - ./mariadb/db.env
    networks:
      - chatbot-network

  chatbot-phpmyadmin:
    image: phpmyadmin
    container_name: "chatbot-phpmyadmin"
    restart: always
    environment:
      PMA_HOST: chatbot-mariadb
    depends_on:
      - chatbot-mariadb
    ports:
      - "127.0.0.1:11090:80"
    networks:
      - chatbot-network

  chatbot-swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: "chatbot-swagger-ui"
    restart: always
    environment:
      PORT_IPV6: 8080
      SUPPORTED_SUBMIT_METHODS: "['get', 'post', 'put', 'delete', 'patch']"
      SWAGGER_JSON: /v1/doc.yaml
    volumes:
      - ./swagger/v1:/v1
    ports:
      - "172.17.0.1:11002:8080"
    networks:
      - chatbot-network



networks:
  chatbot-network:
    driver: bridge
    name: "chatbot-network"
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdff:1:2a::/112
          gateway: fdff:1:2a::1

volumes:
  chatbot-db:
