# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  Chatbot\Infrastructure\LanguageModel\ModelFactory:
    autowire: true
    

  Chatbot\Infrastructure\Api\V1\ChatBotMakeController:
    autowire: true
    arguments:
      $repository: '@conversation.repository'
      $contextrepository: '@context.repository'
      $factory: '@conversation.factory'
      

  Chatbot\Infrastructure\Api\V1\ChatBotContinueController:
    autowire: true
    arguments:
      $repository: '@conversation.repository'
      $contextrepository: '@context.repository'
      $factory: '@conversation.factory'
  
  Chatbot\Infrastructure\Api\V1\ChatBotChangeController:
    autowire: true
    arguments:
      $repository: '@conversation.repository'
      

  Chatbot\Infrastructure\Api\V1\ChatBotMakeContext:
    autowire: true
    arguments:
      $repository: '@context.repository'

  Chatbot\Infrastructure\Api\V1\ChatBotViewContextController:
    autowire: true
    arguments:
      $repository: '@context.repository'
      $convrepository: '@conversation.repository'

  Chatbot\Infrastructure\Api\V1\ChatBotEditContextController:
    autowire: true
    arguments:
      $repository: '@context.repository'

  conversation.repository:
    public: true
    autowire: true
    class: Chatbot\Infrastructure\Persistence\Conversation\ConversationRepositoryDoctrine

  conversation.factory:
    public: true
    autowire: true
    class: Chatbot\Infrastructure\LanguageModel\ModelFactory

  context.repository:
    public: true
    autowire: true
    class: Chatbot\Infrastructure\Persistence\Context\ContextRepositoryDoctrine
       

  Chatbot\Domain\Model\Conversation\ConversationRepositoryInterface: "@conversation.repository"
  Chatbot\Domain\Model\Context\ContextRepositoryInterface: "@context.repository"
  Chatbot\Application\Service\MakeConversation\LanguageModelAbstractFactory: "@conversation.factory"

  
  Chatbot\Infrastructure\Api\V1\:
    resource: "../src/Infrastructure/Api/V1/"
    tags: ["controller.service_arguments"]
    

