openapi: 3.1.0
info:
  title: ChatBot API Documentation
  version: 1.0.0
  description: >-
    Documentation for ChatBot API
servers:
  - url: /api/v1
    description: API routes
  - url: http://172.17.0.1:11080/api/v1
    description: Local Development usage API routes 

tags:
  - name: Conversations
    description: Endpoints related to conversation management
  - name: Context
    description: Endpoints related to context management
  - name: Files
    description: Endpoints related to file management for OpenAI assistants
  - name: Assistant
    description: Endpoints related to OpenAI Assistant management

paths:
  /conversations/Make:
    $ref: conversations/make.yaml
  /conversations/Continue:
    $ref: conversations/continue.yaml
  /conversations:
    $ref: conversations/view.yaml
  
  /context/Make:
    $ref: context/make.yaml
  /contexts:
    $ref: context/manage.yaml
  
  /file/upload:
    $ref: files/upload.yaml
  /file/list:
    $ref: files/list.yaml
  /file/get/{fileId}:
    $ref: files/get.yaml
  /file/delete/{fileId}:
    $ref: files/delete.yaml
  
  /assistant/create-from-context:
    $ref: assistant/create.yaml
  /assistant/{assistant_id}/files:
    $ref: assistant/updateFiles.yaml
  /assistant/{assistant_id}:
    $ref: assistant/delete.yaml
  /assistant/conversation:
    $ref: assistant/conversation.yaml