openapi: 3.1.0
info:
  title: ChatBot API Documentation
  version: 1.0.0
  description: >-
    Documentation for ChatBot API
servers:
  - url: /api/v1
    description: API routes
  - url: http://172.17.0.1:11080/api/v1
    description: Local Development usage API routes 

tags:
  - name: Conversations
    description: Endpoints related to conversation management
  - name: Context
    description: Endpoints related to context management

paths:

  /conversations/Make:
    post:
      tags:
        - Conversations
      summary: Make a conversation
      operationId: makeConversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Prompt:
                  type: string
                  description: The prompt I want to send to the IA
                  example: Bonjour
                lmName:
                  type: string
                  description: The model I want to use
                  example: GPTModel
                context:
                  type: string
                  description: The context id
                  example: cot_66b46fefe29d5

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the conversation was create
                    example: true
                  data:
                    type: object
                    properties:
                      conversationId:
                        type: string
                        description: The ID of the conversation
                        example: con_66c58c7ee6c58
                      numberOfPairs:
                        type: int
                        description: The number of pair in the conversation
                        example: 1
                      botMessage:
                        type: string
                        description: ChatGPT's response.
                        example: Bonjour! Comment puis-je vous aider aujourd'hui?

                    description: Data returned by the make conversation service
          
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  error:
                    type: string
                    description: The message error
                    example: NoIdException
  /conversations/Continue:
    post:
      tags:
        - Conversations
      summary: Continue a conversation
      operationId: continueConversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Prompt:
                  type: string
                  description: The prompt I want to send to the IA
                  example: Bonjour
                convId:
                  type: string
                  description: The id of conversation I want to continue
                  example: con_66680a4a5ee25
                lmName:
                  type: string
                  description: The model I want to use
                  example: GPTModel

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the publication was successful
                    example: true
                  data:
                    type: object
                    properties:
                      conversationId:
                        type: string
                        description: The ID of the conversation
                        example: con_66c58c7ee6c58
                      numberOfPairs:
                        type: int
                        description: The number of pair in the conversation
                        example: 1
                      botMessage:
                        type: string
                        description: ChatGPT's response.
                        example: Bonjour! Comment puis-je vous aider aujourd'hui?
                  description: Data returned by the make conversation service
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  error:
                    type: string
                    description: The message error
                    example: NoIdException
  /conversations:
    get:
      tags:
        - Conversations
      summary: View a conversation
      operationId: viewConversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Id:
                  type: string
                  description: The conversation Id I want to see
                  example: con_66cd76e11574

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the conversation was create
                    example: true
                  data:
                    type: object
                    properties:
                      conversationId:
                        type: string
                        description: The ID of the conversation
                        example: con_66c58c7ee6c58
                      numberOfPairs:
                        type: int
                        description: The number of pair in the conversation
                        example: 1
                      botMessage:
                        type: string
                        description: ChatGPT's response.
                        example: Bonjour! Comment puis-je vous aider aujourd'hui?

                    description: Data returned by the make conversation service
          
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  error:
                    type: string
                    description: The message error
                    example: NoIdException
  
  /context/Make:
    post:
      tags:
          - Context
      summary: Make a context
      operationId: makeContext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ContextMessage:
                  type: string
                  description: The context you want to create to personalize the chatbot's responses.
                  example: Respond like a nextSign salesperson using a formal tone and short sentences.
                

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicate whether the context was changed
                    example: true
                  data:
                    type: object
                    properties:
                      contextId:
                        type: string
                        description: The Id of created Context
                        example: con_664c50f9c95cb
                    description: Data returned by the conversation service
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  error:
                    type: string
                    description: The message error
                    example: EmptyString
  /contexts:
    get:
      tags:
          - Context
      summary: View a context
      operationId: viewContext
      parameters:
      - name: Id
        in: query
        required: true
        schema:
          type: string
          example: cot_66b46fefe29d5
        description: The context you want to view. If you provide a conversation ID, it will retrieve the relevant context.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicate whether the context was changed
                    example: true
                  data:
                    type: object
                    properties:
                      contextMessage:
                        type: string
                        description: The context message of id selected
                        example: I'm a context
                    description: Data returned by the conversation service

        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  error:
                    type: string
                    description: The message error
                    example: NoIdException     
    patch:
      tags:
          - Context
      summary: Modify a context message
      operationId: editContext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Id:
                  type: string
                  description: The context you want to edit.
                  example: cot_66b46fefe29d5
                NewMessage:
                  type: string
                  description: The new context message.
                  example: context
                

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicate whether the context was changed
                    example: true
                  data:
                    type: object
                    properties:
                      contextId:
                        type: string
                        description: The Id of Context
                        example: con_664c50f9c95cb
                      contextMessage:
                        type: string
                        description: The new message for the context
                        example: I'm new context
                    description: Data returned by the conversation service
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  error:
                    type: string
                    description: The message error
                    example: NoIdException
    delete:
      tags:
          - Context
      summary: Delete a context
      operationId: deleteContext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Id:
                  type: string
                  description: The context you want to delete.
                  example: cot_66b46fefe29d5
  
                

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicate whether the context was changed
                    example: true
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                        description: Message explaining whether the context has been removed or not.
                        example: the context was deleted
                    
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  error:
                    type: string
                    description: The message error
                    example: NoIdException