openapi: 3.1.0
info:
  title: ChatBot API Documentation
  version: 1.0.0
  description: >-
    Documentation for ChatBot API
servers:
  - url: /api/v1
    description: API routes
  - url: http://172.17.0.1:11080/api/v1
    description: Local Development usage API routes 

tags:
  - name: Conversations
    description: Endpoints related to conversation management
  - name: Context
    description: Endpoints related to context management

paths:

  /conversations/Make:
    post:
      tags:
        - Conversations
      summary: Make a conversation
      operationId: makeConversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Prompt:
                  type: string
                  description: The prompt I want to send to the IA
                  example: Bonjour
                lmName:
                  type: string
                  description: The model I want to use
                  example: GPTModel
                context:
                  type: string
                  description: The order to the model so that it answers me as I want
                  example: You're a helpful assistant

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the conversation was create
                    example: true
                  statusCode:
                    type: integer
                    description: HTTP status code of the response
                    example: 200
                  data:
                    type: object
                    properties:
                      postId:
                        type: string
                        description: The ID of the conversation
                        example: con_664c50f9c95cb
                    description: Data returned by the publication service
                  message:
                    type: string
                    description: Message associated with the response
                    example: "How can I help you today ?"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  statusCode:
                    type: integer
                    description: HTTP status code of the response
                    example: 400
                  data:
                    type: object
                    description: Data returned by the conversation service
                  message:
                    type: string
                    description: Message associated with the response
                    example: Invalid request
  /conversations/Continue:
    post:
      tags:
        - Conversations
      summary: Continue a conversation
      operationId: continueConversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Prompt:
                  type: string
                  description: The prompt I want to send to the IA
                  example: Bonjour
                convId:
                  type: string
                  description: The id of conversation I want to continue
                  example: con_66680a4a5ee25
                lmName:
                  type: string
                  description: The model I want to use
                  example: GPTModel

      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the publication was successful
                    example: true
                  statusCode:
                    type: integer
                    description: HTTP status code of the response
                    example: 200
                  data:
                    type: object
                    properties:
                      postId:
                        type: string
                        description: The ID of the conversation
                        example: con_664c50f9c95cb
                    description: Data returned by the publication service
                  message:
                    type: string
                    description: Message associated with the response
                    example: "How can I help you today ?"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  statusCode:
                    type: integer
                    description: HTTP status code of the response
                    example: 400
                  data:
                    type: object
                    description: Data returned by the conversation service
                  message:
                    type: string
                    description: Message associated with the response
                    example: Invalid request
  /context/Make:
    post:
      tags:
          - Context
      summary: Make a context
      operationId: makeContext
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ContextMessage:
                  type: string
                  description: The context you want to create to personalize the chatbot's responses.
                  example: Respond like a nextSign salesperson using a formal tone and short sentences.
                

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: indicate if the context was create
                    example: true
                  statusCode:
                    type: integer
                    description: HTTP status code of the response
                    example: 200
                  data:
                    type: object
                    properties:
                      contextId:
                        type: string
                        description: The ID of the context
                        example: cot_664c50f9c95cb
                    description: Data returned by the publication service
                
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates whether the conversation was created
                    example: false
                  statusCode:
                    type: integer
                    description: HTTP status code of the response
                    example: 400
                  data:
                    type: object
                    description: Data returned by the conversation service
                  message:
                    type: string
                    description: Message associated with the response
                    example: Invalid request
